name=eva-motors
version=1.0.0
author=Andrey Gusev
maintainer=Andrey Gusev
sentence=EVA Motors. A modular C++ library for motor and actuator control on Arduino.
paragraph=EVA Motors is a decorator-based library for behavioral modification of micro-motors. EVA Motors lets you compose behavior by stacking decorators that add specific characteristics like S-curve response, inertia simulation, or kick-start pulses
category=Other
url=https://agusevtec.github.io/eva-motors
architectures=*
depends=eva-core-sk
