name=eva-motors
version=1.2.2
author=Andrey Gusev
maintainer=Andrey Gusev
sentence=EVA Motors. Modular decorator-based library for behavioral modification of micro-motors.
paragraph=
category=Device Control
url=https://agusevtec.github.io/eva-motors
architectures=*
depends=eva-core-sk, eva-filters
