name=eva-motors
version=1.1.1
author=Andrey Gusev
maintainer=Andrey Gusev
sentence=EVA Motors.
paragraph=Modular decorator-based library for behavioral modification of micro-motors. 
category=Other
url=https://agusevtec.github.io/eva-motors
architectures=*
depends=eva-core-sk
