site_name: EVA Boxy
site_description: EVA Boxy - GUI windowing library for Arduino Built on EVA Core event-driven framework Create windowed interfaces with buttons, menus, and dialogs
repo_url: https://github.com/agusevtec/eva-core-sk
theme: material
docs_dir: 'docs-md'
site_dir: 'docs'
nav:
  - About: index.md
  - QuickStart:
    - About: index.md

  - API Reference:
      - Classes: eva-core-sk/annotated.md
      - Hierarchy: eva-core-sk/hierarchy.md
      - Files: eva-core-sk/files.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

plugins:
  - search
  - mkdoxy:
      projects:
        eva-core-sk:
          src-dirs: ./src
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "*.h"
            RECURSIVE: True
            EXTRACT_ALL: NO 
            EXTRACT_STRUCT: NO
            EXTRACT_PRIVATE: NO
            EXTRACT_STATIC: YES

